import catalogue from '@/data/books.json';

/*
  The /books catalogue.

  `src/data/books.json` is generated by `scripts/import-epub.py` from the EPUB,
  together with one HTML fragment per chapter under `public/books/<slug>/`.
  The catalogue carries everything the shelf, the book page and the contents
  need (titles, parts, sections, word counts), so none of those screens waits
  on a fetch. Only chapter text is loaded on demand.
*/

export interface BookSection {
  id: string;
  title: string;
  number: string | null;
}

export interface BookChapter {
  id: string;
  title: string;
  number: string | null;
  part: string | null;
  words: number;
  minutes: number;
  sections: BookSection[];
}

export interface Book {
  slug: string;
  title: string;
  subtitle: string | null;
  author: string | null;
  date: string | null;
  description: string | null;
  subjects: string[];
  cover: { src: string; width: number; height: number } | null;
  words: number;
  minutes: number;
  chapters: BookChapter[];
}

export const BOOKS = catalogue as Book[];

export function getBook(slug: string | undefined): Book | undefined {
  return BOOKS.find(b => b.slug === slug);
}

export function chapterIndex(book: Book, chapterId: string | undefined): number {
  return book.chapters.findIndex(c => c.id === chapterId);
}

/** Display label: "Chapter 6", or the title itself for front and back matter. */
export function chapterLabel(chapter: BookChapter): string {
  return chapter.number ? `Chapter ${chapter.number}` : chapter.title;
}

/**
 * Overall progress through the book, weighted by words rather than by chapter
 * count: chapter 6 of SetupTTS is four times the length of chapter 3, and a
 * bar that moved the same amount for both would be lying.
 */
export function bookPercent(book: Book, chapterId: string, position: number): number {
  const i = chapterIndex(book, chapterId);
  if (i < 0 || book.words === 0) return 0;
  let before = 0;
  for (let k = 0; k < i; k++) before += book.chapters[k].words;
  const p = ((before + book.chapters[i].words * clamp01(position)) / book.words) * 100;
  return Math.round(Math.min(100, Math.max(0, p)) * 10) / 10;
}

export function clamp01(n: number): number {
  return Number.isFinite(n) ? Math.min(1, Math.max(0, n)) : 0;
}

/** "2 h 10 min", "45 min". */
export function formatDuration(minutes: number): string {
  if (minutes < 60) return `${minutes} min`;
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return m ? `${h} h ${m} min` : `${h} h`;
}

/** Short title for tight spaces: the part before a colon, if there is one. */
export function shortTitle(book: Book): string {
  return book.title.split(':')[0].trim();
}

export function chapterUrl(slug: string, chapterId: string, hash?: string): string {
  return `/books/${slug}/read/${chapterId}${hash ? `#${hash}` : ''}`;
}

const chapterCache = new Map<string, Promise<string>>();

/** Fetch one chapter fragment. Promises are cached so a prefetch is reused. */
export function loadChapter(slug: string, chapterId: string): Promise<string> {
  const key = `${slug}/${chapterId}`;
  let p = chapterCache.get(key);
  if (!p) {
    p = fetch(`/books/${slug}/chapters/${chapterId}.html`).then(async r => {
      if (!r.ok) throw new Error(`Chapter ${chapterId} could not be loaded (${r.status})`);
      const text = await r.text();
      // A missing file on an SPA host is answered with index.html and a 200.
      // Fragments never start with a doctype, so that is the tell.
      if (/^\s*<!doctype html/i.test(text)) throw new Error(`Chapter ${chapterId} was not found`);
      return text;
    });
    p.catch(() => chapterCache.delete(key));
    chapterCache.set(key, p);
  }
  return p;
}

/** Whole percent, but never "0%" for a book that has been opened. */
export function formatPercent(percent: number): string {
  if (percent <= 0) return '0%';
  if (percent >= 100) return '100%';
  return `${Math.max(1, Math.floor(percent))}%`;
}

/** "just now", "12 min ago", "3 h ago", "yesterday", "3 Oct". */
export function timeAgo(iso: string, now = Date.now()): string {
  const diff = Math.max(0, now - Date.parse(iso));
  const min = Math.floor(diff / 60000);
  if (min < 1) return 'just now';
  if (min < 60) return `${min} min ago`;
  const h = Math.floor(min / 60);
  if (h < 24) return `${h} h ago`;
  if (h < 48) return 'yesterday';
  const d = new Date(iso);
  const sameYear = d.getFullYear() === new Date(now).getFullYear();
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', ...(sameYear ? {} : { year: 'numeric' }) });
}
