// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List security projects",
  description: "List Vijay's cybersecurity portfolio projects, optionally filtered by category or featured status.",
  inputSchema: {
    category: z.string().trim().min(1).optional().describe("Filter by project category."),
    featured: z.boolean().optional().describe("Only return featured projects when true."),
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of projects (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, featured, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("projects").select("id,title,description,category,tech,year,status,featured,key_results,tags,github_link,writeup_link,demo_link").order("year", { ascending: false }).limit(limit ?? 20);
    if (category) query = query.eq("category", category);
    if (featured !== void 0) query = query.eq("featured", featured);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z2 } from "npm:zod@^3.25.76";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project details",
  description: "Fetch the full details of a single portfolio project by its id.",
  inputSchema: {
    id: z2.string().trim().min(1).describe("The project id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("projects").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: `No project found with id "${id}".` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { project: data }
    };
  }
});

// src/lib/mcp/tools/get-my-access.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.3";
var get_my_access_default = defineTool3({
  name: "get_my_access",
  title: "Get my access status",
  description: "Return the signed-in user's portfolio profile and access status (pending, approved, or blocked).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("full_name,email,status,created_at,last_login_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: "No portfolio profile exists yet for this account." }],
        structuredContent: { profile: null }
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/send-contact-message.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z3 } from "npm:zod@^3.25.76";
var send_contact_message_default = defineTool4({
  name: "send_contact_message",
  title: "Send a contact message",
  description: "Send Vijay a message through the portfolio contact inbox as the signed-in user.",
  inputSchema: {
    name: z3.string().trim().min(1).max(100).describe("Sender name."),
    email: z3.string().trim().email().max(255).describe("Sender email address for the reply."),
    subject: z3.string().trim().min(1).max(150).describe("Short subject line."),
    message: z3.string().trim().min(10).max(4e3).describe("Message body.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, email, subject, message }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("contact_messages").insert({ user_id: ctx.getUserId(), name, email, subject, message }).select("id,created_at").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Message sent (id ${data?.id ?? "unknown"}).` }],
      structuredContent: { message: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xyhyqukvfcshqwengxth";
var mcp_default = defineMcp({
  name: "vijaysinghpuwar",
  title: "vijaysinghpuwar",
  version: "0.1.0",
  instructions: "Tools for Vijay Singh Puwar's cybersecurity portfolio. Use `list_projects` and `get_project` to browse security project work, `get_my_access` to check the signed-in user's access status, and `send_contact_message` to reach out.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_projects_default, get_project_default, get_my_access_default, send_contact_message_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.3/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
