// Rebuild trigger: 2026-05-12 — production env var fix
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Defensive fallback: if the build is missing env vars (e.g. .env not bundled),
// fall back to harmless placeholders so module-eval doesn't throw and the public
// portfolio still renders. Auth/db calls will fail individually and be caught
// by their own error handlers.
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // eslint-disable-next-line no-console
  console.error(
    '[supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. ' +
      'Auth and database calls will fail. Check Lovable Cloud → Secrets.'
  );
}

// Temporary diagnostics — remove once OAuth sign-in is confirmed end-to-end.
// eslint-disable-next-line no-console
console.log('[supabase] URL set:', !!import.meta.env.VITE_SUPABASE_URL);
// eslint-disable-next-line no-console
console.log('[supabase] KEY set:', !!import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL ?? 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY ?? 'placeholder-anon-key',
  {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  }
);
