// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Resolution order: VITE_* env vars (preferred — set via .env.local locally,
// or Lovable Cloud → Secrets in deploy) → hardcoded literals (resilience
// against build pipelines that fail to inject env vars; publishable key is
// safe by design).
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ?? 'https://hveucrpuystdvuubaocv.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  'sb_publishable_-qkXIExDAmPoZLFirWiHhw_yjTGdkzW';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  }
);
